### ISSUE TITLE
lottery_workerで起きていたエラー

### ISSUE THREAD

**Issue by tasuren** [RT-Team/rt-bot#199]
```python
Traceback (most recent call last):
  File "/home/tasuren/.local/lib/python3.9/site-packages/nextcord/ext/tasks/__init__.py", line 197, in _loop
    raise exc
  File "/home/tasuren/.local/lib/python3.9/site-packages/nextcord/ext/tasks/__init__.py", line 168, in _loop
    await self.coro(*args, **kwargs)
  File "/home/tasuren/rt/rt-bot/cogs/delay_lottery.py", line 188, in lottery_worker
    await self.bot.cogs["ServerTool"].lottery(
  File "/home/tasuren/.local/lib/python3.9/site-packages/nextcord/ext/commands/core.py", line 507, in __call__
    return await self.callback(self.cog, context, *args, **kwargs)  # type: ignore
  File "/home/tasuren/rt/rt-bot/cogs/server_tool.py", line 372, in lottery
    for member in sample(
  File "/usr/lib/python3.9/random.py", line 450, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
```

**Comment by tasuren** [comment]
修正した。
