### ISSUE TITLE
automodにて発生しているエラーの修正

### ISSUE THREAD

**Issue by tasuren** [RT-Team/rt-bot#216]
```python
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/tasuren/.local/lib/python3.9/site-packages/nextcord/client.py", line 415, in _run_event
    await coro(*args, **kwargs)
  File "/home/tasuren/rt/rt-bot/cogs/automod/__init__.py", line 615, in on_message
    process_check_message(
  File "/home/tasuren/rt/rt-bot/cogs/automod/modutils.py", line 102, in process_check_message
    elif self.update_cache(message) is not None:
  File "/home/tasuren/rt/rt-bot/cogs/automod/cache.py", line 57, in update_cache
    self.before_content = join(self.before or message)
  File "/home/tasuren/rt/rt-bot/cogs/automod/modutils.py", line 27, in join
    "".join(map(lambda x: getattr(embed, x), ("title", "description")))
TypeError: can only concatenate str (not "_EmptyEmbed") to str
```

**Comment by tasuren** [comment]
除去した。
