### ISSUE TITLE
Twitterのエラー

### ISSUE THREAD

**Issue by tasuren** [RT-Team/rt-bot#221]
```python
Task exception was never retrieved
future: <Task finished name='Task-103905406' coro=<TwitterNotification.start_stream() done, defined at /home/tasuren/rt/rt-bot/cogs/twitter.py:220> exception=TypeError("delete() missing 1 required positional argument: 'username'")>
Traceback (most recent call last):
  File "/home/tasuren/rt/rt-bot/cogs/twitter.py", line 231, in start_stream
    follow.append(await self.get_user_id(username))
  File "/home/tasuren/.local/lib/python3.9/site-packages/jishaku/functools.py", line 62, in sync_wrapper
    return await loop.run_in_executor(None, internal_function)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tasuren/rt/rt-bot/cogs/twitter.py", line 218, in get_user_id
    return self.api.get_user(screen_name=username).id_str
  File "/home/tasuren/.local/lib/python3.9/site-packages/tweepy/api.py", line 46, in wrapper
    return method(*args, **kwargs)
  File "/home/tasuren/.local/lib/python3.9/site-packages/tweepy/api.py", line 2426, in get_user
    return self.request(
  File "/home/tasuren/.local/lib/python3.9/site-packages/tweepy/api.py", line 261, in request
    raise NotFound(resp)
tweepy.errors.NotFound: 404 Not Found
50 - User not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tasuren/rt/rt-bot/cogs/twitter.py", line 244, in start_stream
    await self.delete(discord.Object(self.users[username]))
TypeError: delete() missing 1 required positional argument: 'username'
```

**Comment by tasuren** [comment]
これは修正した。
